#!/usr/bin/env bash
# Writes .env.local for local development from the running local Supabase.
# Real keys never go in this file by hand: they come from the cloud environment's
# variables (see .env.example) and are copied here when present.
set -euo pipefail
cd "$(dirname "$0")/.."

status="$(npx supabase status -o env 2>/dev/null)"
get() { printf '%s\n' "$status" | sed -n "s/^$1=\"\(.*\)\"$/\1/p"; }

{
  echo "# Generated by scripts/local-env.sh. Do not commit."
  echo "NEXT_PUBLIC_SUPABASE_URL=$(get API_URL)"
  echo "NEXT_PUBLIC_SUPABASE_ANON_KEY=$(get ANON_KEY)"
  echo "SUPABASE_SERVICE_ROLE_KEY=$(get SERVICE_ROLE_KEY)"
  echo "NEXT_PUBLIC_APP_URL=http://localhost:3000"
  echo "LOCAL_MAILPIT_URL=$(get MAILPIT_URL)"
  echo "CRON_SECRET=${CRON_SECRET:-local-cron-secret-not-for-production}"
  echo "UNSUBSCRIBE_SECRET=${UNSUBSCRIBE_SECRET:-local-unsubscribe-secret-not-for-production}"
  # In the cloud dev environment the Anthropic key is stored as APP_ANTHROPIC_API_KEY so
  # Claude Code itself never picks it up; the app reads ANTHROPIC_API_KEY.
  if [ -n "${APP_ANTHROPIC_API_KEY:-}" ]; then echo "ANTHROPIC_API_KEY=$APP_ANTHROPIC_API_KEY"; fi
  for v in STRIPE_SECRET_KEY STRIPE_WEBHOOK_SECRET STRIPE_PRICE_ID NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY \
           RESEND_API_KEY EMAIL_FROM NEXT_PUBLIC_POSTHOG_KEY NEXT_PUBLIC_POSTHOG_HOST SENTRY_DSN; do
    if [ -n "${!v:-}" ]; then echo "$v=${!v}"; fi
  done
} > .env.local

echo "Wrote .env.local"
